apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: socket-gateway
  name: socket-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: socket-gateway
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/docker_network: "true"
        io.kompose.service: socket-gateway
    spec:
      containers:
      - args:
        - python
        - ./gateway.py
        env:
        - name: IN_CONTAINER_FLAG
          value: "1"
        image: socket-gateway
        imagePullPolicy: ""
        name: socket-gateway
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
